// action-types.js
// const must be unique, ModuleName.ActionType
export const LOGGED_IN = "AUTH.LOGGED_IN";
export const LOGGED_OUT = "AUTH.LOGGED_OUT";

export const INCREMENT = "COUNTER.INCREMENT";
export const RESET = "COUNTER.RESET";

export const INIT_PRODUCTS = "PRODUCT.INIT_PRODUCTS";
export const LOADING_PRODUCTS="PRODUCT.LOADING_PRODUCTS"

export const REQUEST_PRODUCTS = "PRODUCT.REQUEST_PRODUCTS";
export const DELETE_PRODUCT = "PRODUCT.DELETE_PRODUCT";
export const DELETE_RELOAD_PRODUCTS = "PRODUCT.DELETE_RELOAD_PRODUCTS";
